# Verify that the software builds on a Mac either with English or Japanese
# enabled.

name: test-mac-build

on:
  push:
    branches: [ 'check-ranges' ]
  pull_request:

jobs:
  english:
    name: English
    runs-on: macos-13

    steps:
      - name: Clone Project
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.3.app
          cd src
          make -f Makefile.std
